version: '3.8'

services:
  urlshortener:
    build: ./
    command: -db postgresql  # параметры запуска сервра
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=0000

  db:
    restart: always
    build: ./shema
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"
volumes:
  db: